# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# fail_fast: true
exclude: ^Phase2/ScaffoldingFilesNotModified/$|^Phase2/PseudoCodeFunctions/$
repos:
-   repo: local
    hooks:
    - id: generate-compile-commands-src
      name: Generate compile_commands.json for /src/
      entry: src/update-compile-commands.sh
      language: script
      pass_filenames: false
-   repo: local
    hooks:
    - id: generate-compile-commands-scaffoldingFilesChanged
      name: Generate compile_commands.json for /Phase2/ScaffoldingFilesChanged
      entry: Phase2/ScaffoldingFilesChanged/update-compile-commands.sh
      language: script
      pass_filenames: false
- repo: local
  hooks:
  - id: flawfinder
    name: flawfinder security scanner
    description: 'Scan C/C++ code for potential security vulnerabilities'
    entry: flawfinder --error-level=3
    language: system
    files: \.(c|cpp|h|hpp)$
    exclude: (\.md$|^Phase2/ScaffoldingFilesNotModified/|stubs\.c$|bogus_main\.c$|db\.h$|account\.h$|login\.h$|logging\.h$|banned\.h$)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: uncrustify
        exclude: (\.md$|^Phase2/ScaffoldingFilesNotModified/|stubs\.c$|bogus_main\.c$|db\.h$|account\.h$|login\.h$|logging\.h$|banned\.h$)
        args: ["-c", ".github/workflows/uncrustify.cfg", "--replace", "--no-backup"]
      - id: clang-tidy
        exclude: (\.md$|^Phase2/ScaffoldingFilesNotModified/|^Phase2/PseudoCodeFunctions/|stubs\.c$|bogus_main\.c$|db\.h$|account\.h$|login\.h$|logging\.h$|banned\.h$)
        args: ["--fix-errors", "-warnings-as-errors=*"]
      - id: cppcheck
        exclude: (\.md$|^Phase2/ScaffoldingFilesNotModified/|^Phase2/PseudoCodeFunctions/|stubs\.c$|bogus_main\.c$|db\.h$|account\.h$|login\.h$|logging\.h$|banned\.h$)
      - id: cpplint
        exclude: (\.md$|^Phase2/ScaffoldingFilesNotModified/|stubs\.c$|bogus_main\.c$|db\.h$|account\.h$|login\.h$|logging\.h$|banned\.h$)
        args: ["--filter=+build,-legal,+readablity,+runtime,-whitespace/indent,-build/include_alpha,-whitespace/braces,-whitespace/comments,-whitespace/newline,-readability/braces,-whitespace/tab,-whitespace/line_length,-build/include_subdir"]
