name: Formatting
description: Checks C code formatting using uncrustify

inputs:
  path:
    description: 'Path to check'
    required: false
    default: './'
  
runs:
  using: "composite"
  steps:
    - name: Run uncrustify check
      uses: Daniel-Trevitz/uncrustify-check@v1
      shell: bash
      with:
        configFile: 'uncrustify.cfg'
