name: Formatting

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.c'
      - '**.h'

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest
    name: Check C Styling
    
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        
    - name: uncrustify check
      uses: Daniel-Trevitz/uncrustify-check@v1
      with:
        configFile: 'uncrustify.cfg'
