name: Code Formatting Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    paths:
      - '**.c'
      - '**.h'
  workflow_dispatch:  # For manual runs

jobs:
  format_check:
    runs-on: ubuntu-latest
    name: Uncrustify Code Format Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run formatting check
        uses: ./.github/actions/formatting/uncrustify
